services:
  frontend:
    build: "./frontend"
    container_name: sqli1_frontend
    ports:
      - 1337:1337
    depends_on:
      - db
    environment:
      - FLAG=MINUTEMAN{TEST}
  db:
    image: mysql:9.0.1
    container_name: sqli1_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: c4cc207db461462f8e22aa3ddc744b66
      MYSQL_DATABASE: user_db